# Generated by Django 5.0.7 on 2026-07-02 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aliado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
            ],
            options={
                "verbose_name": "aliado",
                "verbose_name_plural": "aliados",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cobertura_clc",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="cobertura CLC (Corine Land Cover)",
                    ),
                ),
                (
                    "cobertura_nombre_comun",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="nombre común de cobertura",
                    ),
                ),
                (
                    "clima_koeppen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Selva_tropical_lluviosa", "Selva tropical lluviosa"),
                            ("Monzon_tropical", "Monzón tropical"),
                            ("Sabana_tropical", "Sabana tropical"),
                            ("Desierto_IC", "Desierto (IC)"),
                            ("Desierto_IF", "Desierto (IF)"),
                            (
                                "Oceanico_de_la_costa_occidental_VC",
                                "Oceánico costa occidental (VC)",
                            ),
                            (
                                "Oceanico_de_la_costa_occidental_VF",
                                "Oceánico costa occidental (VF)",
                            ),
                            ("Templado_de_montania_VC", "Templado de montaña (VC)"),
                            ("Templado_de_montania_VF", "Templado de montaña (VF)"),
                            ("Continental_humedo", "Continental húmedo"),
                            (
                                "Continental_de_verano_calido",
                                "Continental verano cálido",
                            ),
                            ("Continental_seco_VC", "Continental seco (VC)"),
                            (
                                "Continental_de_verano_calido_2",
                                "Continental verano cálido (2)",
                            ),
                            ("Continental_seco_VF", "Continental seco (VF)"),
                            ("Continental_humedo_1", "Continental húmedo (1)"),
                            (
                                "Continental_de_verano_calido_3",
                                "Continental verano cálido (3)",
                            ),
                            ("Casquete_de_hielo", "Casquete de hielo"),
                            ("Tundra", "Tundra"),
                        ],
                        max_length=50,
                        verbose_name="clima Köppen",
                    ),
                ),
                (
                    "cobertura_igbp",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Vegetacion_escasa_o_suelo_desnudo",
                                "Vegetación escasa o suelo desnudo",
                            ),
                            ("Cultivos", "Cultivos"),
                            ("Matorrales_cerrados", "Matorrales cerrados"),
                            (
                                "Mosaico_de_cultivos_y_vegetacion_natural",
                                "Mosaico de cultivos y vegetación natural",
                            ),
                            (
                                "Bosques_latifoliados_caducifolios",
                                "Bosques latifoliados caducifolios",
                            ),
                            (
                                "Bosques_de_coniferas_caducifolias",
                                "Bosques de coníferas caducifolias",
                            ),
                            (
                                "Bosques_latifoliados_siempreverdes",
                                "Bosques latifoliados siempreverdes",
                            ),
                            (
                                "Bosques_de_coniferas_siempreverdes",
                                "Bosques de coníferas siempreverdes",
                            ),
                            ("Pastizales", "Pastizales"),
                            ("Bosques_mixtos", "Bosques mixtos"),
                            ("Matorrales_abiertos", "Matorrales abiertos"),
                            ("Sabanas", "Sabanas"),
                            ("Nieve_y_hielo", "Nieve y hielo"),
                            (
                                "Areas_urbanas_y_construidas",
                                "Áreas urbanas y construidas",
                            ),
                            ("Cuerpos_de_agua", "Cuerpos de agua"),
                            ("Humedales_permanentes", "Humedales permanentes"),
                            ("Sabanas_arboladas", "Sabanas arboladas"),
                        ],
                        max_length=60,
                        verbose_name="cobertura IGBP",
                    ),
                ),
            ],
            options={
                "verbose_name": "cobertura",
                "verbose_name_plural": "coberturas",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionSensorGas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gas",
                    models.CharField(
                        choices=[("CO2", "CO₂"), ("CH4", "CH₄"), ("N2O", "N₂O")],
                        max_length=4,
                        verbose_name="gas",
                    ),
                ),
                (
                    "longitud_tubo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="longitud del tubo (cm)",
                    ),
                ),
                (
                    "diametro_tubo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="diámetro del tubo (mm)",
                    ),
                ),
                (
                    "separacion_norte_sur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="separación N–S (m)",
                    ),
                ),
                (
                    "separacion_este_oeste",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="separación E–O (m)",
                    ),
                ),
                (
                    "separacion_vertical",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="separación vertical (m)",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración sensor de gas",
                "verbose_name_plural": "configuraciones sensores de gas",
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Amazonas", "Amazonas"),
                            ("Antioquia", "Antioquia"),
                            ("Arauca", "Arauca"),
                            ("Atlantico", "Atlántico"),
                            ("Bolivar", "Bolívar"),
                            ("Boyaca", "Boyacá"),
                            ("Caldas", "Caldas"),
                            ("Caqueta", "Caquetá"),
                            ("Casanare", "Casanare"),
                            ("Cauca", "Cauca"),
                            ("Cesar", "Cesar"),
                            ("Choco", "Chocó"),
                            ("Cordoba", "Córdoba"),
                            ("Cundinamarca", "Cundinamarca"),
                            ("Guainia", "Guainía"),
                            ("Guaviare", "Guaviare"),
                            ("Huila", "Huila"),
                            ("La_Guajira", "La Guajira"),
                            ("Magdalena", "Magdalena"),
                            ("Meta", "Meta"),
                            ("Narinio", "Nariño"),
                            ("Norte_de_Santander", "Norte de Santander"),
                            ("Putumayo", "Putumayo"),
                            ("Quindio", "Quindío"),
                            ("Risaralda", "Risaralda"),
                            ("San_Andres", "San Andrés, Providencia y Santa Catalina"),
                            ("Santander", "Santander"),
                            ("Sucre", "Sucre"),
                            ("Tolima", "Tolima"),
                            ("Valle_del_Cauca", "Valle del Cauca"),
                            ("Vaupes", "Vaupés"),
                            ("Vichada", "Vichada"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "departamento",
                "verbose_name_plural": "departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_equipo",
                    models.CharField(
                        choices=[
                            ("Anemometro", "Anemómetro"),
                            ("Analizador_CO2", "Analizador CO₂"),
                            ("Analizador_CH4", "Analizador CH₄"),
                            ("Adquisicion", "Adquisición"),
                            ("Retencion", "Retención"),
                            ("Procesamiento", "Procesamiento"),
                            ("Biomet", "Biomet"),
                            ("Estacion_Complementaria", "Estación complementaria"),
                        ],
                        max_length=30,
                        verbose_name="tipo de equipo",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "serial",
                    models.CharField(blank=True, max_length=120, verbose_name="serial"),
                ),
            ],
            options={
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
                "ordering": ["torre", "tipo_equipo"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(max_length=80, unique=True, verbose_name="código"),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "coordinador",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="coordinador"
                    ),
                ),
                (
                    "correo_coordinador",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="correo del coordinador",
                    ),
                ),
                (
                    "sitio",
                    models.TextField(blank=True, verbose_name="descripción del sitio"),
                ),
                (
                    "abreviatura_sitio",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="abreviatura del sitio"
                    ),
                ),
                (
                    "objetivo_general",
                    models.TextField(blank=True, verbose_name="objetivo general"),
                ),
                (
                    "preguntas_principales",
                    models.TextField(blank=True, verbose_name="preguntas principales"),
                ),
                (
                    "escala_espacial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bioma", "Bioma"),
                            ("Regional", "Regional"),
                            ("Ecosistema", "Ecosistema"),
                            ("Sitio", "Sitio"),
                            ("Parcela", "Parcela"),
                        ],
                        max_length=20,
                        verbose_name="escala espacial",
                    ),
                ),
                (
                    "numero_sitios_monitoreo",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="número de sitios de monitoreo",
                    ),
                ),
                (
                    "estructura_muestreo",
                    models.TextField(blank=True, verbose_name="estructura de muestreo"),
                ),
                (
                    "tipo_diseno",
                    models.TextField(blank=True, verbose_name="tipo de diseño"),
                ),
                (
                    "objetivo_especifico",
                    models.TextField(blank=True, verbose_name="objetivo específico"),
                ),
            ],
            options={
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bibliography_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="tipo de referencia"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="ISBN"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=255, verbose_name="DOI"),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="identificador"
                    ),
                ),
                ("titulo", models.TextField(verbose_name="título")),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="revista / journal"
                    ),
                ),
                (
                    "volumen",
                    models.CharField(blank=True, max_length=20, verbose_name="volumen"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="número"),
                ),
                (
                    "paginas",
                    models.CharField(blank=True, max_length=40, verbose_name="páginas"),
                ),
                (
                    "anio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="año"
                    ),
                ),
                (
                    "mes",
                    models.CharField(blank=True, max_length=20, verbose_name="mes"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email de contacto"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=2048, verbose_name="URL"),
                ),
                ("abstract", models.TextField(blank=True, verbose_name="resumen")),
                (
                    "keywords",
                    models.TextField(blank=True, verbose_name="palabras clave"),
                ),
                (
                    "validacion_campo",
                    models.BooleanField(
                        default=False, verbose_name="validación en campo"
                    ),
                ),
                (
                    "datos_disponibles_repositorio",
                    models.BooleanField(
                        default=False, verbose_name="datos disponibles en repositorio"
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación",
                "verbose_name_plural": "publicaciones",
                "ordering": ["-anio", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Andes", "Andes"),
                            ("Orinoquia", "Orinoquía"),
                            ("Amazonas", "Amazonas"),
                            ("Caribe", "Caribe"),
                            ("Pacifico", "Pacífico"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "región",
                "verbose_name_plural": "regiones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SistemaReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("EPSG_4326", "EPSG:4326 — WGS84"),
                            ("EPSG_4686", "EPSG:4686 — MAGNA-SIRGAS"),
                            ("EPSG_4674", "EPSG:4674 — SIRGAS2000"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "sistema de referencia",
                "verbose_name_plural": "sistemas de referencia",
            },
        ),
        migrations.CreateModel(
            name="Vegetacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_cobertura",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pasto_Graminea", "Pasto / Gramínea"),
                            ("Graminea_C3", "Gramínea C3"),
                            ("Graminea_C4", "Gramínea C4"),
                            ("Cultivo_herbaceo", "Cultivo herbáceo"),
                            ("Cultivo_lenoso", "Cultivo leñoso"),
                            ("Arbol", "Árbol"),
                            ("Arbol_caducifolio", "Árbol caducifolio"),
                            ("Arbol_perennifolio", "Árbol perennifolio"),
                            ("Arbusto", "Arbusto"),
                            ("Hierba_Forbia", "Hierba / Forbia"),
                            (
                                "Hierba_anual_Forbia_anual",
                                "Hierba anual / Forbia anual",
                            ),
                            (
                                "Hierba_perenne_Forbia_perenne",
                                "Hierba perenne / Forbia perenne",
                            ),
                            ("Plantas_con_aerenquima", "Plantas con aerénquima"),
                            ("Liana_Enredadera", "Liana / Enredadera"),
                            ("Suculenta", "Suculenta"),
                            ("No_vasculares", "No vasculares"),
                            ("Otro", "Otro"),
                            ("Sin_vegetacion", "Sin vegetación"),
                            ("Agua", "Agua"),
                        ],
                        max_length=40,
                        verbose_name="tipo de cobertura",
                    ),
                ),
                (
                    "especies_dominantes",
                    models.TextField(blank=True, verbose_name="especies dominantes"),
                ),
                (
                    "altura_dosel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="altura del dosel (m)",
                    ),
                ),
                (
                    "porcentaje_cobertura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% cobertura",
                    ),
                ),
                (
                    "edad_cobertura",
                    models.TextField(blank=True, verbose_name="edad de la cobertura"),
                ),
                (
                    "estado_sucesional",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="estado sucesional"
                    ),
                ),
            ],
            options={
                "verbose_name": "vegetación",
                "verbose_name_plural": "vegetaciones",
            },
        ),
        migrations.CreateModel(
            name="Disturbio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "incertidumbre_anios",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="incertidumbre (años)"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Agricultura", "Agricultura"),
                            ("Sequia", "Sequía"),
                            ("Fuego", "Fuego"),
                            ("Silvicultura", "Silvicultura"),
                            ("Pastoreo", "Pastoreo"),
                            ("Evento_hidrologico", "Evento hidrológico"),
                            (
                                "Cambio_en_cobertura_del_suelo",
                                "Cambio en cobertura del suelo",
                            ),
                            ("Plagas_y_enfermedades", "Plagas y enfermedades"),
                            ("Tormenta_o_viento", "Tormenta o viento"),
                            ("Extremos_de_temperatura", "Extremos de temperatura"),
                            ("Sin_disturbio", "Sin disturbio"),
                        ],
                        default="Sin_disturbio",
                        max_length=40,
                        verbose_name="tipo de disturbio",
                    ),
                ),
                (
                    "anios_disturbio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="años de disturbio"
                    ),
                ),
                (
                    "anios_desde_fin",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="años desde fin del disturbio",
                    ),
                ),
                (
                    "estado_actual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Intacto", "Intacto"),
                            ("Ligeramente_degradado", "Ligeramente degradado"),
                            ("Moderadamente_degradado", "Moderadamente degradado"),
                            ("Severamente_degradado", "Severamente degradado"),
                            ("En_recuperacion_natural", "En recuperación natural"),
                            ("En_restauracion_activa", "En restauración activa"),
                            ("Estable", "Estable"),
                            ("En_transicion", "En transición"),
                        ],
                        max_length=30,
                        verbose_name="estado actual",
                    ),
                ),
            ],
            options={
                "verbose_name": "disturbio",
                "verbose_name_plural": "disturbios",
                "indexes": [
                    models.Index(fields=["tipo"], name="app_disturb_tipo_4d2785_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=160)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipios",
                        to="app.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "municipio",
                "verbose_name_plural": "municipios",
                "ordering": ["departamento__nombre", "nombre"],
                "unique_together": {("nombre", "departamento")},
            },
        ),
        migrations.CreateModel(
            name="ProyectoAliado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.aliado"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.proyecto"
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto aliado",
                "verbose_name_plural": "proyectos aliados",
                "unique_together": {("proyecto", "aliado")},
            },
        ),
        migrations.AddField(
            model_name="proyecto",
            name="aliados",
            field=models.ManyToManyField(
                blank=True,
                related_name="proyectos",
                through="app.ProyectoAliado",
                to="app.aliado",
            ),
        ),
        migrations.CreateModel(
            name="PublicacionAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.autor"
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.publicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación-autor",
                "verbose_name_plural": "publicaciones-autores",
                "unique_together": {("publicacion", "autor")},
            },
        ),
        migrations.AddField(
            model_name="publicacion",
            name="autores",
            field=models.ManyToManyField(
                blank=True,
                related_name="publicaciones",
                through="app.PublicacionAutor",
                to="app.autor",
            ),
        ),
        migrations.AddField(
            model_name="departamento",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departamentos",
                to="app.region",
            ),
        ),
        migrations.CreateModel(
            name="ResultadoPublicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variable",
                    models.CharField(
                        choices=[
                            ("Biomasa_Aerea_C", "Biomasa aérea (C)"),
                            ("Biomasa_Subterranea_C", "Biomasa subterránea (C)"),
                            ("Biomasa_Total_C", "Biomasa total (C)"),
                            ("COS", "Carbono orgánico del suelo (COS)"),
                            ("MOM", "MOM"),
                            ("AMP_TM", "AMP TM"),
                            ("DFM", "DFM"),
                            ("DGM", "DGM"),
                            ("Hojarasca", "Hojarasca"),
                            ("CO2_Flux", "Flujo CO₂"),
                            ("CH4_Flux", "Flujo CH₄"),
                            ("N2O_Flux", "Flujo N₂O"),
                        ],
                        max_length=30,
                        verbose_name="variable",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="valor",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(blank=True, max_length=80, verbose_name="unidad"),
                ),
                (
                    "error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="error",
                    ),
                ),
                (
                    "metodologia",
                    models.TextField(blank=True, verbose_name="metodología"),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="app.publicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de publicación",
                "verbose_name_plural": "resultados de publicación",
                "ordering": ["publicacion", "variable"],
            },
        ),
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_metadatos",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="código de metadatos"
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="latitud"
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="longitud"
                    ),
                ),
                (
                    "altitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="altitud (m.s.n.m.)",
                    ),
                ),
                (
                    "pendiente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plano", "Plano"),
                            ("ondulado_variable", "Ondulado / variable"),
                            ("valle_fondo", "Valle / fondo"),
                            ("pendiente_suave", "Pendiente suave (<2%)"),
                            ("pendiente_media", "Pendiente media (2–5%)"),
                            (
                                "pendiente_significativa",
                                "Pendiente significativa (5–10%)",
                            ),
                            ("pendiente_fuerte", "Pendiente fuerte (>10%)"),
                            ("cresta_cima", "Cresta / cima"),
                        ],
                        max_length=30,
                        verbose_name="pendiente",
                    ),
                ),
                (
                    "topografia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cresta_cima", "Cresta / cima"),
                            ("ladera_superior", "Ladera superior"),
                            ("ladera_media", "Ladera media"),
                            ("ladera_inferior", "Ladera inferior"),
                            ("valle_fondo", "Valle / fondo"),
                            ("plano", "Plano"),
                        ],
                        max_length=24,
                        verbose_name="topografía",
                    ),
                ),
                (
                    "uso_actual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bosque_primario", "Bosque primario"),
                            ("Bosque_secundario", "Bosque secundario"),
                            ("Plantacion_forestal", "Plantación forestal"),
                            ("Agricultura_intensiva", "Agricultura intensiva"),
                            ("Agricultura_tradicional", "Agricultura tradicional"),
                            ("Pastura", "Pastura"),
                            ("Humedal_natural", "Humedal natural"),
                            ("Humedal_intervenido", "Humedal intervenido"),
                            ("Area_protegida", "Área protegida"),
                            ("Sistema_agroforestal", "Sistema agroforestal"),
                            ("Abandonado", "Abandonado"),
                            ("Restauracion_activa", "Restauración activa"),
                        ],
                        max_length=30,
                        verbose_name="uso actual del suelo",
                    ),
                ),
                (
                    "propiedad_tierra",
                    models.CharField(
                        blank=True,
                        choices=[("publica", "Pública"), ("privada", "Privada")],
                        max_length=10,
                        verbose_name="propiedad de la tierra",
                    ),
                ),
                (
                    "intervenido",
                    models.BooleanField(default=False, verbose_name="intervenido"),
                ),
                (
                    "cobertura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to="app.cobertura",
                    ),
                ),
                (
                    "disturbio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to="app.disturbio",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sitios",
                        to="app.municipio",
                    ),
                ),
                (
                    "sistema_referencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sitios",
                        to="app.sistemareferencia",
                    ),
                ),
                (
                    "vegetacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to="app.vegetacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitio",
                "verbose_name_plural": "sitios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PublicacionSitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.publicacion",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sitio"
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación-sitio",
                "verbose_name_plural": "publicaciones-sitios",
                "unique_together": {("publicacion", "sitio")},
            },
        ),
        migrations.AddField(
            model_name="publicacion",
            name="sitios",
            field=models.ManyToManyField(
                blank=True,
                related_name="publicaciones",
                through="app.PublicacionSitio",
                to="app.sitio",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="sitio_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos",
                to="app.sitio",
                verbose_name="sitio principal",
            ),
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unidad_muestreo",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Parcela_permanente_cuadrada",
                                "Parcela permanente cuadrada",
                            ),
                            (
                                "Parcela_permanente_rectangular",
                                "Parcela permanente rectangular",
                            ),
                            ("Parcela_circular", "Parcela circular"),
                            ("Transecto_lineal", "Transecto lineal"),
                            (
                                "Puntos_de_muestreo_aleatorios",
                                "Puntos de muestreo aleatorios",
                            ),
                            ("Conglomerado", "Conglomerado"),
                        ],
                        max_length=40,
                        verbose_name="unidad de muestreo",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="área (m²)",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Activa", "Activa"),
                            ("Inactiva", "Inactiva"),
                            ("Abandonada", "Abandonada"),
                            ("Finalizada", "Finalizada"),
                        ],
                        max_length=20,
                        verbose_name="estatus",
                    ),
                ),
                (
                    "fecha_instalacion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="año de instalación"
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelas",
                        to="app.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela",
                "verbose_name_plural": "parcelas",
                "ordering": ["sitio", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FuenteDatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx / .xls)"),
                            ("csv", "CSV"),
                            ("shapefile", "Shapefile (.shp)"),
                            ("geojson", "GeoJSON"),
                            ("api", "API externa"),
                            ("base_de_datos", "Base de datos"),
                            ("otro", "Otro"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="enlace al archivo"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente — sin procesar"),
                            ("en_proceso", "En proceso"),
                            ("completo", "Completo"),
                            ("con_errores", "Con errores"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="responsable"
                    ),
                ),
                (
                    "fecha_datos",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de los datos"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuentes_datos",
                        to="app.proyecto",
                        verbose_name="proyecto",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuentes_datos",
                        to="app.sitio",
                        verbose_name="sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente de datos",
                "verbose_name_plural": "fuentes de datos",
                "ordering": ["proyecto", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CaracterizacionMuestreoSuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "muestreo_id",
                    models.PositiveIntegerField(verbose_name="ID de muestreo"),
                ),
                (
                    "tipo_de_suelo",
                    models.CharField(
                        blank=True,
                        choices=[("Mineral", "Mineral"), ("Organico", "Orgánico")],
                        max_length=10,
                        verbose_name="tipo de suelo",
                    ),
                ),
                (
                    "profundidad_perfil",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="profundidad del perfil (cm)",
                    ),
                ),
                (
                    "intervalos_perfil",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="intervalos del perfil (cm)",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caracterizaciones_suelo",
                        to="app.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "caracterización muestreo suelo",
                "verbose_name_plural": "caracterizaciones muestreo suelo",
                "ordering": ["sitio", "muestreo_id"],
            },
        ),
        migrations.CreateModel(
            name="TorreEc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fecha_instalacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de instalación"
                    ),
                ),
                (
                    "utc",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="UTC offset"
                    ),
                ),
                (
                    "altura_canopy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="altura del canopy (m)",
                    ),
                ),
                (
                    "altura_torre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="altura de la torre (m)",
                    ),
                ),
                (
                    "altura_anemometro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="altura del anemómetro (m)",
                    ),
                ),
                (
                    "frecuencia_adquisicion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="frecuencia de adquisición (Hz)",
                    ),
                ),
                (
                    "north_offset",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="north offset (°)",
                    ),
                ),
                (
                    "longitud_tubo_sensor_co2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="longitud tubo sensor CO₂ (cm)",
                    ),
                ),
                (
                    "diametro_tubo_sensor_co2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="diámetro tubo sensor CO₂ (mm)",
                    ),
                ),
                (
                    "configuracion_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.configuracionsensorgas",
                        verbose_name="configuración principal",
                    ),
                ),
                (
                    "equipo_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.equipo",
                        verbose_name="equipo principal",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="torres_ec",
                        to="app.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "torre EC",
                "verbose_name_plural": "torres EC",
                "ordering": ["sitio"],
            },
        ),
        migrations.AddField(
            model_name="equipo",
            name="torre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos",
                to="app.torreec",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsensorgas",
            name="torre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuraciones_gas",
                to="app.torreec",
            ),
        ),
        migrations.CreateModel(
            name="TorreFuenteEnergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_fuente",
                    models.CharField(
                        choices=[
                            ("generador_metanol", "Generador metanol"),
                            ("generador_gasolina", "Generador gasolina"),
                            ("solar_mas_generador", "Solar + generador"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="tipo de fuente",
                    ),
                ),
                (
                    "numero_unidades_recepcion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="unidades de recepción"
                    ),
                ),
                (
                    "numero_unidades_almacenamiento",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="unidades de almacenamiento"
                    ),
                ),
                (
                    "sistema_puesta_tierra",
                    models.BooleanField(
                        default=False, verbose_name="sistema de puesta a tierra"
                    ),
                ),
                (
                    "torre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_energia",
                        to="app.torreec",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente de energía",
                "verbose_name_plural": "fuentes de energía",
            },
        ),
        migrations.CreateModel(
            name="Transecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descripción"
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transectos",
                        to="app.parcela",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transectos",
                        to="app.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "transecto",
                "verbose_name_plural": "transectos",
                "ordering": ["sitio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MonitoreoSuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("Macrofosiles", "Macrofósiles"),
                            ("Datacion", "Datación"),
                            ("Densidad_Aparente", "Densidad aparente"),
                            ("COS", "Carbono orgánico del suelo (COS)"),
                        ],
                        max_length=20,
                        verbose_name="tipo de monitoreo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "protocolo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="protocolo"
                    ),
                ),
                (
                    "caracterizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoreos",
                        to="app.caracterizacionmuestreosuelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitoreo de suelo",
                "verbose_name_plural": "monitoreos de suelo",
                "unique_together": {("caracterizacion", "tipo_monitoreo")},
            },
        ),
        migrations.CreateModel(
            name="MonitoreoParcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("Biomasa_Aerea", "Biomasa aérea"),
                            ("Biomasa_Subterranea", "Biomasa subterránea"),
                            ("Flora", "Flora"),
                            ("Rasgos_Funcionales", "Rasgos funcionales"),
                        ],
                        max_length=30,
                        verbose_name="tipo de monitoreo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "protocolo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alometria_destructiva", "Alometría destructiva"),
                            ("Alometria_no_destructiva", "Alometría no destructiva"),
                            ("LiDAR_terrestre", "LiDAR terrestre"),
                            ("LiDAR_aerotransportado", "LiDAR aerotransportado"),
                        ],
                        max_length=40,
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoreos",
                        to="app.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitoreo de parcela",
                "verbose_name_plural": "monitoreos de parcela",
                "unique_together": {("parcela", "tipo_monitoreo")},
            },
        ),
        migrations.CreateModel(
            name="FlujoCamaras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camara_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de cámara"
                    ),
                ),
                (
                    "microtopografia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Hummock", "Hummock (cojines)"),
                            ("Hollow", "Hollow (depresiones húmedas)"),
                            ("Pool", "Pool (charcos / sobre agua)"),
                            ("Lawns", "Lawns (lugares planos)"),
                        ],
                        max_length=10,
                        verbose_name="microtopografía",
                    ),
                ),
                (
                    "diametro_anillo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="diámetro del anillo (cm)",
                    ),
                ),
                (
                    "tratamiento",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="tratamiento"
                    ),
                ),
                (
                    "pozo_nivel_freatico",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="pozo / nivel freático"
                    ),
                ),
                (
                    "cobertura_vegetal_primaria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pasto_Graminea", "Pasto / Gramínea"),
                            ("Graminea_C3", "Gramínea C3"),
                            ("Graminea_C4", "Gramínea C4"),
                            ("Cultivo_herbaceo", "Cultivo herbáceo"),
                            ("Cultivo_lenoso", "Cultivo leñoso"),
                            ("Arbol", "Árbol"),
                            ("Arbol_caducifolio", "Árbol caducifolio"),
                            ("Arbol_perennifolio", "Árbol perennifolio"),
                            ("Arbusto", "Arbusto"),
                            ("Hierba_Forbia", "Hierba / Forbia"),
                            (
                                "Hierba_anual_Forbia_anual",
                                "Hierba anual / Forbia anual",
                            ),
                            (
                                "Hierba_perenne_Forbia_perenne",
                                "Hierba perenne / Forbia perenne",
                            ),
                            ("Plantas_con_aerenquima", "Plantas con aerénquima"),
                            ("Liana_Enredadera", "Liana / Enredadera"),
                            ("Suculenta", "Suculenta"),
                            ("No_vasculares", "No vasculares"),
                            ("Otro", "Otro"),
                            ("Sin_vegetacion", "Sin vegetación"),
                            ("Agua", "Agua"),
                        ],
                        max_length=40,
                        verbose_name="cobertura vegetal primaria",
                    ),
                ),
                (
                    "porcentaje_cob_veg_pri",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% cobertura primaria",
                    ),
                ),
                (
                    "cobertura_vegetal_secundaria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pasto_Graminea", "Pasto / Gramínea"),
                            ("Graminea_C3", "Gramínea C3"),
                            ("Graminea_C4", "Gramínea C4"),
                            ("Cultivo_herbaceo", "Cultivo herbáceo"),
                            ("Cultivo_lenoso", "Cultivo leñoso"),
                            ("Arbol", "Árbol"),
                            ("Arbol_caducifolio", "Árbol caducifolio"),
                            ("Arbol_perennifolio", "Árbol perennifolio"),
                            ("Arbusto", "Arbusto"),
                            ("Hierba_Forbia", "Hierba / Forbia"),
                            (
                                "Hierba_anual_Forbia_anual",
                                "Hierba anual / Forbia anual",
                            ),
                            (
                                "Hierba_perenne_Forbia_perenne",
                                "Hierba perenne / Forbia perenne",
                            ),
                            ("Plantas_con_aerenquima", "Plantas con aerénquima"),
                            ("Liana_Enredadera", "Liana / Enredadera"),
                            ("Suculenta", "Suculenta"),
                            ("No_vasculares", "No vasculares"),
                            ("Otro", "Otro"),
                            ("Sin_vegetacion", "Sin vegetación"),
                            ("Agua", "Agua"),
                        ],
                        max_length=40,
                        verbose_name="cobertura vegetal secundaria",
                    ),
                ),
                (
                    "porcentaje_cob_veg_sec",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% cobertura secundaria",
                    ),
                ),
                (
                    "cobertura_vegetal_terciaria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pasto_Graminea", "Pasto / Gramínea"),
                            ("Graminea_C3", "Gramínea C3"),
                            ("Graminea_C4", "Gramínea C4"),
                            ("Cultivo_herbaceo", "Cultivo herbáceo"),
                            ("Cultivo_lenoso", "Cultivo leñoso"),
                            ("Arbol", "Árbol"),
                            ("Arbol_caducifolio", "Árbol caducifolio"),
                            ("Arbol_perennifolio", "Árbol perennifolio"),
                            ("Arbusto", "Arbusto"),
                            ("Hierba_Forbia", "Hierba / Forbia"),
                            (
                                "Hierba_anual_Forbia_anual",
                                "Hierba anual / Forbia anual",
                            ),
                            (
                                "Hierba_perenne_Forbia_perenne",
                                "Hierba perenne / Forbia perenne",
                            ),
                            ("Plantas_con_aerenquima", "Plantas con aerénquima"),
                            ("Liana_Enredadera", "Liana / Enredadera"),
                            ("Suculenta", "Suculenta"),
                            ("No_vasculares", "No vasculares"),
                            ("Otro", "Otro"),
                            ("Sin_vegetacion", "Sin vegetación"),
                            ("Agua", "Agua"),
                        ],
                        max_length=40,
                        verbose_name="cobertura vegetal terciaria",
                    ),
                ),
                (
                    "porcentaje_cob_veg_ter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% cobertura terciaria",
                    ),
                ),
                (
                    "distancia_drenaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="distancia a drenaje (m)",
                    ),
                ),
                (
                    "distancia_fuego",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="distancia a fuego (m)",
                    ),
                ),
                (
                    "distancia_pastoreo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="distancia a pastoreo (m)",
                    ),
                ),
                (
                    "distancia_cultivo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="distancia a cultivo (m)",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flujos_camara",
                        to="app.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "flujo cámaras",
                "verbose_name_plural": "flujos cámaras",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sitio"], name="app_flujoca_sitio_i_a6706f_idx"
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="configuracionsensorgas",
            unique_together={("torre", "gas")},
        ),
    ]
