# Generated by Django 5.0.7 on 2026-06-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='app_emissio_year_f4fa2c_idx',
            old_name='emissions_e_year_e5e10c_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='app_emissio_region__c6abe4_idx',
            old_name='emissions_e_region__b35ace_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='app_emissio_sector__1a62ee_idx',
            old_name='emissions_e_sector__bc1b56_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='app_emissio_gas_id_033822_idx',
            old_name='emissions_e_gas_id_d1e897_idx',
        ),
    ]
