# Generated by Django 5.0.7 on 2026-07-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reportador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "correo_institucional",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo institucional"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo personal"
                    ),
                ),
                (
                    "institucion_asociada",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="institución asociada"
                    ),
                ),
            ],
            options={
                "verbose_name": "reportador",
                "verbose_name_plural": "reportadores",
                "ordering": ["nombre"],
            },
        ),
        migrations.RemoveField(
            model_name="fuentedatos",
            name="fecha_datos",
        ),
        migrations.RemoveField(
            model_name="fuentedatos",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="fuentedatos",
            name="sitio",
        ),
        migrations.AddField(
            model_name="fuentedatos",
            name="fecha_recepcion",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.AddField(
            model_name="fuentedatos",
            name="reportador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuentes_datos",
                to="app.reportador",
                verbose_name="reportador",
            ),
        ),
    ]
