# Generated by Django 5.0.7 on 2026-06-16 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emissions_e_year_e5e10c_idx_app_emissio_year_f4fa2c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre del proyecto')),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='código del proyecto')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SitioMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_sitio', models.CharField(max_length=80, verbose_name='código del sitio')),
                ('unidad_muestreo', models.CharField(blank=True, max_length=80, verbose_name='unidad de muestreo')),
                ('region_natural', models.CharField(choices=[('andes', 'Andes'), ('orinoquia', 'Orinoquia'), ('amazonas', 'Amazonas'), ('caribe', 'Caribe'), ('pacifico', 'Pacífico')], max_length=24, verbose_name='región natural')),
                ('ecosistema', models.CharField(choices=[('paramo_seco', 'Páramo seco'), ('turbera_alta_elevacion', 'Turbera de alta elevación'), ('bosque_humedo_tropical', 'Bosque húmedo tropical'), ('bosque_de_niebla', 'Bosque de niebla'), ('bosque_seco_tropical', 'Bosque seco tropical'), ('sabana_seca', 'Sabana seca'), ('sabana_inundable', 'Sabana inundable'), ('turbera_baja_elevacion', 'Turbera de baja elevación'), ('pantano_cienaga', 'Pantano / ciénaga'), ('lago_superficial', 'Lago superficial'), ('manglar', 'Manglar')], max_length=40, verbose_name='ecosistema')),
                ('departamento', models.CharField(choices=[('amazonas', 'Amazonas'), ('antioquia', 'Antioquia'), ('arauca', 'Arauca'), ('atlantico', 'Atlántico'), ('bolivar', 'Bolívar'), ('boyaca', 'Boyacá'), ('caldas', 'Caldas'), ('caqueta', 'Caquetá'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Chocó'), ('cordoba', 'Córdoba'), ('cundinamarca', 'Cundinamarca'), ('guainia', 'Guainía'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('la_guajira', 'La Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('narino', 'Nariño'), ('norte_de_santander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindío'), ('risaralda', 'Risaralda'), ('san_andres', 'San Andrés, Providencia y Santa Catalina'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle_del_cauca', 'Valle del Cauca'), ('vaupes', 'Vaupés'), ('vichada', 'Vichada')], max_length=40, verbose_name='departamento')),
                ('sitio_urbano_cercano', models.CharField(blank=True, max_length=160, verbose_name='sitio urbano cercano')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='longitud')),
                ('sistema_referencia', models.CharField(choices=[('EPSG:4326', 'EPSG:4326 — WGS84'), ('EPSG:4686', 'EPSG:4686 — MAGNA-SIRGAS'), ('EPSG:4674', 'EPSG:4674 — SIRGAS2000'), ('otro', 'Otro (indicar código EPSG)')], default='EPSG:4326', max_length=16, verbose_name='sistema de referencia')),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='altitud (m.s.n.m.)')),
                ('pendiente', models.CharField(blank=True, choices=[('plano', 'Plano'), ('ondulado_variable', 'Ondulado / variable'), ('pendiente_suave', 'Pendiente suave (<2%)'), ('pendiente_media', 'Pendiente media (2–5%)'), ('pendiente_significativa', 'Pendiente significativa (5–10%)'), ('pendiente_fuerte', 'Pendiente fuerte (>10%)'), ('cresta_cima', 'Cresta / cima')], max_length=30, verbose_name='pendiente')),
                ('topografia', models.CharField(blank=True, choices=[('cresta_cima', 'Cresta / cima'), ('ladera_superior', 'Ladera superior'), ('ladera_media', 'Ladera media'), ('ladera_inferior', 'Ladera inferior'), ('valle_fondo', 'Valle / fondo'), ('plano', 'Plano')], max_length=24, verbose_name='topografía')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sitios', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'sitio de monitoreo',
                'verbose_name_plural': 'sitios de monitoreo',
                'ordering': ['proyecto', 'codigo_sitio'],
                'unique_together': {('proyecto', 'codigo_sitio')},
            },
        ),
        migrations.CreateModel(
            name='RegistroFlujoCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_metadatos', models.CharField(max_length=80, unique=True, verbose_name='código de metadatos')),
                ('cobertura_ipcc', models.CharField(blank=True, max_length=120, verbose_name='cobertura IPCC')),
                ('cobertura_clc', models.CharField(blank=True, max_length=120, verbose_name='cobertura CLC (Corine Land Cover)')),
                ('cobertura_igbp', models.CharField(blank=True, max_length=120, verbose_name='cobertura IGBP')),
                ('cobertura_nom_comun', models.CharField(blank=True, max_length=160, verbose_name='nombre común de cobertura')),
                ('clima_koeppen', models.CharField(blank=True, choices=[('selva_tropical_lluviosa', 'Selva tropical lluviosa'), ('monzon_tropical', 'Monzón tropical'), ('sabana_tropical', 'Sabana tropical'), ('desierto_IC', 'Desierto (IC)'), ('desierto_IF', 'Desierto (IF)'), ('oceanico_VC', 'Oceánico costa occidental (VC)'), ('oceanico_VF', 'Oceánico costa occidental (VF)'), ('montania_VC', 'Templado de montaña (VC)'), ('montania_VF', 'Templado de montaña (VF)'), ('continental_humedo', 'Continental húmedo'), ('continental_verano_calido', 'Continental verano cálido'), ('continental_seco_VC', 'Continental seco (VC)'), ('continental_seco_VF', 'Continental seco (VF)'), ('tundra', 'Tundra'), ('casquete_hielo', 'Casquete de hielo')], max_length=30, verbose_name='clima Köppen')),
                ('tipo_disturbio', models.CharField(choices=[('agricultura', 'Agricultura'), ('sequia', 'Sequía'), ('fuego', 'Fuego'), ('silvicultura', 'Silvicultura'), ('pastoreo', 'Pastoreo'), ('evento_hidrologico', 'Evento hidrológico'), ('cambio_cobertura', 'Cambio en cobertura del suelo'), ('plagas_enfermedades', 'Plagas y enfermedades'), ('tormenta_viento', 'Tormenta o viento'), ('extremos_temperatura', 'Extremos de temperatura'), ('sin_disturbio', 'Sin disturbio')], default='sin_disturbio', max_length=30, verbose_name='tipo de disturbio')),
                ('anios_disturbio', models.PositiveIntegerField(blank=True, null=True, verbose_name='años de disturbio')),
                ('anios_desde_fin_disturbio', models.PositiveIntegerField(blank=True, null=True, verbose_name='años desde fin del disturbio')),
                ('uso_actual', models.CharField(blank=True, choices=[('bosque_primario', 'Bosque primario'), ('bosque_secundario', 'Bosque secundario'), ('plantacion_forestal', 'Plantación forestal'), ('agricultura_intensiva', 'Agricultura intensiva'), ('agricultura_tradicional', 'Agricultura tradicional'), ('pastura', 'Pastura'), ('humedal_natural', 'Humedal natural'), ('humedal_intervenido', 'Humedal intervenido'), ('area_protegida', 'Área protegida'), ('sistema_agroforestal', 'Sistema agroforestal'), ('abandonado', 'Abandonado'), ('restauracion_activa', 'Restauración activa')], max_length=30, verbose_name='uso actual del suelo')),
                ('estado_actual', models.CharField(blank=True, choices=[('intacto', 'Intacto'), ('ligeramente_degradado', 'Ligeramente degradado'), ('moderadamente_degradado', 'Moderadamente degradado'), ('severamente_degradado', 'Severamente degradado'), ('en_recuperacion_natural', 'En recuperación natural'), ('en_restauracion_activa', 'En restauración activa'), ('estable', 'Estable'), ('en_transicion', 'En transición')], max_length=30, verbose_name='estado actual')),
                ('propiedad_tierra', models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=10, verbose_name='propiedad de la tierra')),
                ('tipo_de_suelo', models.CharField(blank=True, choices=[('mineral', 'Mineral'), ('organico', 'Orgánico')], max_length=10, verbose_name='tipo de suelo')),
                ('microtopografia', models.CharField(blank=True, choices=[('hummock', 'Hummock (cojines)'), ('hollow', 'Hollow (depresiones húmedas)'), ('pool', 'Pool (charcos / sobre agua)'), ('lawns', 'Lawns (lugares planos)')], max_length=10, verbose_name='microtopografía')),
                ('diametro_anillo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diámetro del anillo (cm)')),
                ('tratamiento', models.CharField(blank=True, max_length=255, verbose_name='tratamiento')),
                ('pozo_nivel_freatico', models.CharField(blank=True, max_length=80, verbose_name='pozo / nivel freático')),
                ('cobertura_vegetal_primaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal primaria')),
                ('porcentaje_cob_veg_pri', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura primaria')),
                ('cobertura_vegetal_secundaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal secundaria')),
                ('porcentaje_cob_veg_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura secundaria')),
                ('cobertura_vegetal_terciaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal terciaria')),
                ('porcentaje_cob_veg_ter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura terciaria')),
                ('distancia_drenaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a drenaje (m)')),
                ('distancia_fuego', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a fuego (m)')),
                ('distancia_pastoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a pastoreo (m)')),
                ('distancia_cultivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a cultivo (m)')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='app.sitiomonitoreo')),
            ],
            options={
                'verbose_name': 'registro flujo cámara',
                'verbose_name_plural': 'registros flujo cámara',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sitio'], name='app_registr_sitio_i_0b3602_idx'), models.Index(fields=['tipo_disturbio'], name='app_registr_tipo_di_2b3d23_idx'), models.Index(fields=['uso_actual'], name='app_registr_uso_act_ac6f40_idx')],
            },
        ),
    ]
