# Generated by Django 5.0.7 on 2026-07-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_reportador_remove_fuentedatos_fecha_datos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archivo",
                    models.FileField(upload_to="cargas/%Y/%m/", verbose_name="archivo"),
                ),
                (
                    "hoja_activa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="hoja activa"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("subido", "Archivo subido"),
                            ("mapeado", "Mapeo definido"),
                            ("validado", "Validación completada"),
                            ("importado", "Importado a BD"),
                        ],
                        default="subido",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "columnas_raw",
                    models.JSONField(
                        default=list, verbose_name="columnas inspeccionadas"
                    ),
                ),
                (
                    "total_filas",
                    models.IntegerField(default=0, verbose_name="total de filas"),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas",
                        to="app.fuentedatos",
                        verbose_name="fuente de datos",
                    ),
                ),
            ],
            options={
                "verbose_name": "carga de archivo",
                "verbose_name_plural": "cargas de archivos",
                "ordering": ["-created_at"],
            },
        ),
    ]
