# Generated by Django 5.0.7 on 2026-07-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_cargaarchivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapeoColumna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "columna_origen",
                    models.CharField(max_length=255, verbose_name="columna origen"),
                ),
                (
                    "modelo_destino",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="modelo destino"
                    ),
                ),
                (
                    "campo_destino",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="campo destino"
                    ),
                ),
                (
                    "transformacion",
                    models.CharField(
                        choices=[
                            ("directo", "Directo"),
                            ("lookup", "Lookup / FK"),
                            ("split", "Split"),
                            ("fecha", "Parsear fecha"),
                            ("ignorar", "Ignorar"),
                        ],
                        default="directo",
                        max_length=20,
                        verbose_name="transformación",
                    ),
                ),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeos",
                        to="app.cargaarchivo",
                        verbose_name="carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "mapeo de columna",
                "verbose_name_plural": "mapeos de columnas",
                "ordering": ["columna_origen"],
                "unique_together": {("carga", "columna_origen")},
            },
        ),
    ]
