# Generated by Django 5.0.7 on 2026-06-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proyecto_sitiomonitoreo_registroflujocamara'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroflujocamara',
            name='cobertura_humedal',
            field=models.CharField(blank=True, choices=[('turbera_musgo', 'Turbera de musgo (bog)'), ('turbera_pantanosa', 'Turbera pantanosa (fen)'), ('pantano_arbolado', 'Pantano arbolado (swamp)'), ('marisma', 'Marisma / estuario'), ('manglar', 'Manglar'), ('lago_laguna', 'Lago / laguna'), ('rio_ripario', 'Río / zona riparia'), ('sabana_inundable', 'Sabana inundable'), ('arrozal', 'Arrozal'), ('no_aplica', 'No aplica')], max_length=30, verbose_name='cobertura de humedal'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='intervalos_perfil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='intervalos del perfil (cm)'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='monitoreo_cos',
            field=models.BooleanField(default=False, verbose_name='monitoreo de carbono orgánico del suelo (COS)'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='monitoreo_datacion',
            field=models.BooleanField(default=False, verbose_name='monitoreo de datación'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='monitoreo_densidad_aparente',
            field=models.BooleanField(default=False, verbose_name='monitoreo de densidad aparente'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='monitoreo_macrofosiles',
            field=models.BooleanField(default=False, verbose_name='monitoreo de macrofósiles'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='profundidad_perfil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='profundidad del perfil (cm)'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='protocolo_cos',
            field=models.CharField(blank=True, choices=[('loss_on_ignition', 'Pérdida por ignición (LOI)'), ('walkley_black', 'Walkley-Black (oxidación húmeda)'), ('combustion_seca', 'Combustión seca (analizador elemental)'), ('espectroscopia_nir', 'Espectroscopía NIR/MIR'), ('otro', 'Otro (especificar en notas)')], max_length=30, verbose_name='protocolo COS'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='protocolo_datacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='protocolo datación'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='protocolo_densidad_aparente',
            field=models.CharField(blank=True, choices=[('anillo_volumetrico', 'Anillo volumétrico (core ring)'), ('terrón_parafina', 'Terrón parafinado'), ('cilindro_driving', 'Cilindro tipo driving'), ('otro', 'Otro (especificar en notas)')], max_length=30, verbose_name='protocolo densidad aparente'),
        ),
        migrations.AddField(
            model_name='registroflujocamara',
            name='protocolo_macrofosiles',
            field=models.CharField(blank=True, max_length=255, verbose_name='protocolo macrofósiles'),
        ),
    ]
