# Generated by Django 5.0.7 on 2026-06-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registroflujocamara_cobertura_humedal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_de_suelo', models.CharField(blank=True, choices=[('mineral', 'Mineral'), ('organico', 'Orgánico')], max_length=10, verbose_name='tipo de suelo')),
                ('microtopografia', models.CharField(blank=True, choices=[('hummock', 'Hummock (cojines)'), ('hollow', 'Hollow (depresiones húmedas)'), ('pool', 'Pool (charcos / sobre agua)'), ('lawns', 'Lawns (lugares planos)')], max_length=10, verbose_name='microtopografía')),
                ('diametro_anillo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diámetro del anillo (cm)')),
                ('tratamiento', models.CharField(blank=True, max_length=255, verbose_name='tratamiento')),
                ('pozo_nivel_freatico', models.CharField(blank=True, max_length=80, verbose_name='pozo / nivel freático')),
            ],
            options={
                'verbose_name': 'caracterización',
                'verbose_name_plural': 'caracterizaciones',
            },
        ),
        migrations.CreateModel(
            name='CaracterizacionMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profundidad_perfil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='profundidad del perfil (cm)')),
                ('intervalos_perfil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='intervalos del perfil (cm)')),
                ('monitoreo_macrofosiles', models.BooleanField(default=False, verbose_name='monitoreo de macrofósiles')),
                ('protocolo_macrofosiles', models.CharField(blank=True, max_length=255, verbose_name='protocolo macrofósiles')),
                ('monitoreo_datacion', models.BooleanField(default=False, verbose_name='monitoreo de datación')),
                ('protocolo_datacion', models.CharField(blank=True, max_length=255, verbose_name='protocolo datación')),
                ('monitoreo_densidad_aparente', models.BooleanField(default=False, verbose_name='monitoreo de densidad aparente')),
                ('protocolo_densidad_aparente', models.CharField(blank=True, choices=[('anillo_volumetrico', 'Anillo volumétrico (core ring)'), ('terron_parafina', 'Terrón parafinado'), ('cilindro_driving', 'Cilindro tipo driving'), ('otro', 'Otro (especificar en notas)')], max_length=30, verbose_name='protocolo densidad aparente')),
                ('monitoreo_cos', models.BooleanField(default=False, verbose_name='monitoreo de carbono orgánico del suelo (COS)')),
                ('protocolo_cos', models.CharField(blank=True, choices=[('loss_on_ignition', 'Pérdida por ignición (LOI)'), ('walkley_black', 'Walkley-Black (oxidación húmeda)'), ('combustion_seca', 'Combustión seca (analizador elemental)'), ('espectroscopia_nir', 'Espectroscopía NIR/MIR'), ('otro', 'Otro (especificar en notas)')], max_length=30, verbose_name='protocolo COS')),
            ],
            options={
                'verbose_name': 'caracterización muestreo',
                'verbose_name_plural': 'caracterizaciones muestreo',
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cobertura_ipcc', models.CharField(blank=True, max_length=120, verbose_name='cobertura IPCC')),
                ('cobertura_clc', models.CharField(blank=True, max_length=120, verbose_name='cobertura CLC (Corine Land Cover)')),
                ('cobertura_igbp', models.CharField(blank=True, max_length=120, verbose_name='cobertura IGBP')),
                ('cobertura_nom_comun', models.CharField(blank=True, max_length=160, verbose_name='nombre común de cobertura')),
                ('cobertura_humedal', models.CharField(blank=True, choices=[('turbera_musgo', 'Turbera de musgo (bog)'), ('turbera_pantanosa', 'Turbera pantanosa (fen)'), ('pantano_arbolado', 'Pantano arbolado (swamp)'), ('marisma', 'Marisma / estuario'), ('manglar', 'Manglar'), ('lago_laguna', 'Lago / laguna'), ('rio_ripario', 'Río / zona riparia'), ('sabana_inundable', 'Sabana inundable'), ('arrozal', 'Arrozal'), ('no_aplica', 'No aplica')], max_length=30, verbose_name='cobertura de humedal')),
                ('clima_koeppen', models.CharField(blank=True, choices=[('selva_tropical_lluviosa', 'Selva tropical lluviosa'), ('monzon_tropical', 'Monzón tropical'), ('sabana_tropical', 'Sabana tropical'), ('desierto_IC', 'Desierto (IC)'), ('desierto_IF', 'Desierto (IF)'), ('oceanico_VC', 'Oceánico costa occidental (VC)'), ('oceanico_VF', 'Oceánico costa occidental (VF)'), ('montania_VC', 'Templado de montaña (VC)'), ('montania_VF', 'Templado de montaña (VF)'), ('continental_humedo', 'Continental húmedo'), ('continental_verano_calido', 'Continental verano cálido'), ('continental_seco_VC', 'Continental seco (VC)'), ('continental_seco_VF', 'Continental seco (VF)'), ('tundra', 'Tundra'), ('casquete_hielo', 'Casquete de hielo')], max_length=30, verbose_name='clima Köppen')),
            ],
            options={
                'verbose_name': 'cobertura',
                'verbose_name_plural': 'coberturas',
            },
        ),
        migrations.CreateModel(
            name='Distancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distancia_drenaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a drenaje (m)')),
                ('distancia_fuego', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a fuego (m)')),
                ('distancia_pastoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a pastoreo (m)')),
                ('distancia_cultivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia a cultivo (m)')),
            ],
            options={
                'verbose_name': 'distancias',
                'verbose_name_plural': 'distancias',
            },
        ),
        migrations.CreateModel(
            name='Disturbio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_disturbio', models.CharField(choices=[('agricultura', 'Agricultura'), ('sequia', 'Sequía'), ('fuego', 'Fuego'), ('silvicultura', 'Silvicultura'), ('pastoreo', 'Pastoreo'), ('evento_hidrologico', 'Evento hidrológico'), ('cambio_cobertura', 'Cambio en cobertura del suelo'), ('plagas_enfermedades', 'Plagas y enfermedades'), ('tormenta_viento', 'Tormenta o viento'), ('extremos_temperatura', 'Extremos de temperatura'), ('sin_disturbio', 'Sin disturbio')], default='sin_disturbio', max_length=30, verbose_name='tipo de disturbio')),
                ('anios_disturbio', models.PositiveIntegerField(blank=True, null=True, verbose_name='años de disturbio')),
                ('anios_desde_fin_disturbio', models.PositiveIntegerField(blank=True, null=True, verbose_name='años desde fin del disturbio')),
                ('uso_actual', models.CharField(blank=True, choices=[('bosque_primario', 'Bosque primario'), ('bosque_secundario', 'Bosque secundario'), ('plantacion_forestal', 'Plantación forestal'), ('agricultura_intensiva', 'Agricultura intensiva'), ('agricultura_tradicional', 'Agricultura tradicional'), ('pastura', 'Pastura'), ('humedal_natural', 'Humedal natural'), ('humedal_intervenido', 'Humedal intervenido'), ('area_protegida', 'Área protegida'), ('sistema_agroforestal', 'Sistema agroforestal'), ('abandonado', 'Abandonado'), ('restauracion_activa', 'Restauración activa')], max_length=30, verbose_name='uso actual del suelo')),
                ('estado_actual', models.CharField(blank=True, choices=[('intacto', 'Intacto'), ('ligeramente_degradado', 'Ligeramente degradado'), ('moderadamente_degradado', 'Moderadamente degradado'), ('severamente_degradado', 'Severamente degradado'), ('en_recuperacion_natural', 'En recuperación natural'), ('en_restauracion_activa', 'En restauración activa'), ('estable', 'Estable'), ('en_transicion', 'En transición')], max_length=30, verbose_name='estado actual')),
                ('propiedad_tierra', models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=10, verbose_name='propiedad de la tierra')),
            ],
            options={
                'verbose_name': 'disturbio',
                'verbose_name_plural': 'disturbios',
            },
        ),
        migrations.CreateModel(
            name='VegetacionAnillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cobertura_vegetal_primaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal primaria')),
                ('porcentaje_cob_veg_pri', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura primaria')),
                ('cobertura_vegetal_secundaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal secundaria')),
                ('porcentaje_cob_veg_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura secundaria')),
                ('cobertura_vegetal_terciaria', models.CharField(blank=True, max_length=160, verbose_name='cobertura vegetal terciaria')),
                ('porcentaje_cob_veg_ter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% cobertura terciaria')),
            ],
            options={
                'verbose_name': 'vegetación anillo',
                'verbose_name_plural': 'vegetaciones anillo',
            },
        ),
        migrations.RemoveIndex(
            model_name='registroflujocamara',
            name='app_registr_tipo_di_2b3d23_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroflujocamara',
            name='app_registr_uso_act_ac6f40_idx',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='anios_desde_fin_disturbio',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='anios_disturbio',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='clima_koeppen',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_clc',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_humedal',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_igbp',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_ipcc',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_nom_comun',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_vegetal_primaria',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_vegetal_secundaria',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='cobertura_vegetal_terciaria',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='diametro_anillo',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='distancia_cultivo',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='distancia_drenaje',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='distancia_fuego',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='distancia_pastoreo',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='intervalos_perfil',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='microtopografia',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='monitoreo_cos',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='monitoreo_datacion',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='monitoreo_densidad_aparente',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='monitoreo_macrofosiles',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='porcentaje_cob_veg_pri',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='porcentaje_cob_veg_sec',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='porcentaje_cob_veg_ter',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='pozo_nivel_freatico',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='profundidad_perfil',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='propiedad_tierra',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='protocolo_cos',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='protocolo_datacion',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='protocolo_densidad_aparente',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='protocolo_macrofosiles',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='tipo_de_suelo',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='tipo_disturbio',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='registroflujocamara',
            name='uso_actual',
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion', to='app.registroflujocamara'),
        ),
        migrations.AddField(
            model_name='caracterizacionmuestreo',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion_muestreo', to='app.registroflujocamara'),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobertura', to='app.registroflujocamara'),
        ),
        migrations.AddField(
            model_name='distancias',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distancias', to='app.registroflujocamara'),
        ),
        migrations.AddField(
            model_name='disturbio',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disturbio', to='app.registroflujocamara'),
        ),
        migrations.AddField(
            model_name='vegetacionanillo',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vegetacion_anillo', to='app.registroflujocamara'),
        ),
        migrations.AddIndex(
            model_name='disturbio',
            index=models.Index(fields=['tipo_disturbio'], name='app_disturb_tipo_di_daf815_idx'),
        ),
        migrations.AddIndex(
            model_name='disturbio',
            index=models.Index(fields=['uso_actual'], name='app_disturb_uso_act_895f7a_idx'),
        ),
    ]
