# Generated by Django 5.0.7 on 2026-06-16 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_caracterizacion_caracterizacionmuestreo_cobertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura', to='app.registroflujocamara'),
        ),
        migrations.AlterField(
            model_name='disturbio',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbio', to='app.registroflujocamara'),
        ),
        migrations.CreateModel(
            name='RegistroBiomasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_metadatos', models.CharField(max_length=80, unique=True, verbose_name='código de metadatos')),
                ('parcela', models.CharField(blank=True, max_length=80, verbose_name='parcela')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_biomasa', to='app.sitiomonitoreo')),
            ],
            options={
                'verbose_name': 'registro biomasa',
                'verbose_name_plural': 'registros biomasa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaracterizacionParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_de_muestreo', models.CharField(blank=True, choices=[('parcela_circular', 'Parcela circular'), ('parcela_cuadrada', 'Parcela cuadrada'), ('transecto', 'Transecto lineal'), ('punto_radio_fijo', 'Punto de radio fijo'), ('banda', 'Banda / franja'), ('otra', 'Otra (especificar en notas)')], max_length=30, verbose_name='unidad de muestreo')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='área (m²)')),
                ('estatus_parcela', models.CharField(blank=True, choices=[('activa', 'Activa — en monitoreo regular'), ('inactiva', 'Inactiva — sin monitoreo activo'), ('abandonada', 'Abandonada — sin posibilidad de continuar'), ('nueva', 'Nueva — instalada pero sin mediciones'), ('en_restauracion', 'En restauración')], max_length=20, verbose_name='estatus de la parcela')),
                ('fecha_instalacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='año de instalación')),
                ('monitoreo_biomasa_aerea', models.BooleanField(default=False, verbose_name='monitoreo de biomasa aérea')),
                ('protocolo_biomasa_aerea', models.CharField(blank=True, choices=[('ecuaciones_alometricas', 'Ecuaciones alométricas (modelos regionales o locales)'), ('inventario_forestal_completo', 'Inventario forestal completo (DAP, altura, densidad)'), ('cosecha_destructiva', 'Cosecha destructiva (pesaje de biomasa fresca y seca)'), ('teledeteccion_lidar', 'Teledetección / LiDAR (estimación remota de estructura)'), ('otro', 'Otro (especificar en notas)')], max_length=40, verbose_name='protocolo biomasa aérea')),
                ('monitoreo_biomasa_subterranea', models.BooleanField(default=False, verbose_name='monitoreo de biomasa subterránea')),
                ('protocolo_biomasa_subterranea', models.CharField(blank=True, max_length=255, verbose_name='protocolo biomasa subterránea')),
                ('monitoreo_flora', models.BooleanField(default=False, verbose_name='monitoreo de flora')),
                ('protocolo_flora', models.CharField(blank=True, max_length=255, verbose_name='protocolo flora')),
                ('monitoreo_rasgos_funcionales', models.BooleanField(default=False, verbose_name='monitoreo de rasgos funcionales')),
                ('protocolo_rasgos_funcionales', models.CharField(blank=True, max_length=255, verbose_name='protocolo rasgos funcionales')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion_parcela', to='app.registrobiomasa')),
            ],
            options={
                'verbose_name': 'caracterización de parcela',
                'verbose_name_plural': 'caracterizaciones de parcela',
            },
        ),
        migrations.AddField(
            model_name='cobertura',
            name='registro_biomasa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura', to='app.registrobiomasa'),
        ),
        migrations.AddField(
            model_name='disturbio',
            name='registro_biomasa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbio', to='app.registrobiomasa'),
        ),
        migrations.AddIndex(
            model_name='registrobiomasa',
            index=models.Index(fields=['sitio'], name='app_registr_sitio_i_cf6ed8_idx'),
        ),
    ]
