# Generated by Django 5.0.7 on 2026-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_publicaciontype_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapeocolumna",
            name="mapeo_valores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Traduce valores de origen a choices del campo destino. Ej: {"Journal Article": "articulo_revista"}',
                verbose_name="mapeo de valores",
            ),
        ),
    ]
