# Generated by Django 5.0.7 on 2026-07-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_cargaarchivo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='codigo',
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_rol', to='app.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_usuario', to='app.rolusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_rol', to='app.usuario')),
            ],
            options={
                'verbose_name': 'proyecto usuario',
                'verbose_name_plural': 'proyectos usuarios',
                'unique_together': {('proyecto', 'usuario', 'rol')},
            },
        ),
    ]
