# Generated by Django 5.0.7 on 2026-07-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_proyecto_codigo_proyectousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('soil_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='temperatura del suelo (°C)')),
                ('air_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='temperatura del aire (°C)')),
                ('atm_press', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='presión atmosférica (hPa)')),
                ('relat_humid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='humedad relativa (%)')),
                ('dew_point', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='punto de rocío (°C)')),
                ('microtopo', models.CharField(blank=True, choices=[('Hummock', 'Hummock (cojines)'), ('Hollow', 'Hollow (depresiones húmedas)'), ('Pool', 'Pool (charcos / sobre agua)'), ('Lawns', 'Lawns (lugares planos)')], max_length=10, verbose_name='microtopografía')),
            ],
            options={
                'verbose_name': 'muestra ambiental',
                'verbose_name_plural': 'muestras ambientales',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='código')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('magnitud', models.CharField(blank=True, help_text='flujo, concentración, temperatura, …', max_length=60, verbose_name='magnitud')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Anillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diametro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diámetro (cm)')),
                ('volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='volumen (cm³)')),
                ('unidad_muestreo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anillos', to='app.parcela', verbose_name='unidad de muestreo (parcela)')),
            ],
            options={
                'verbose_name': 'anillo',
                'verbose_name_plural': 'anillos',
                'ordering': ['unidad_muestreo', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, verbose_name='código')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='app.equipo', verbose_name='equipo (picarro)')),
            ],
            options={
                'verbose_name': 'cámara',
                'verbose_name_plural': 'cámaras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MuestraCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('anillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.anillo', verbose_name='anillo')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.camara', verbose_name='cámara')),
                ('muestra_ambiental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_co2', to='app.muestraambiental', verbose_name='muestra ambiental')),
            ],
            options={
                'verbose_name': 'muestra CO₂',
                'verbose_name_plural': 'muestras CO₂',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmuestraCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_toma', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número de toma')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora de la toma')),
                ('momento', models.CharField(blank=True, choices=[('inicio', 'Inicio'), ('final', 'Final')], max_length=10, verbose_name='momento')),
                ('condicion_luz', models.CharField(blank=True, choices=[('dia', 'Día'), ('noche', 'Noche'), ('noche_simulada', 'Noche simulada (cobija)')], max_length=15, verbose_name='condición de luz')),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='valor del flujo')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submuestras', to='app.muestraco2', verbose_name='muestra CO₂')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submuestras_co2', to='app.unidadmedida', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'submuestra CO₂',
                'verbose_name_plural': 'submuestras CO₂',
                'ordering': ['muestra', 'n_toma'],
            },
        ),
        migrations.AddIndex(
            model_name='muestraco2',
            index=models.Index(fields=['anillo'], name='app_muestra_anillo__4f7987_idx'),
        ),
        migrations.AddIndex(
            model_name='muestraco2',
            index=models.Index(fields=['camara'], name='app_muestra_camara__96dce6_idx'),
        ),
    ]
