# Generated by Django 5.0.7 on 2026-07-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_muestraambiental_unidadmedida_anillo_camara_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlujoCamaras',
        ),
    ]
