# Generated by Django 5.0.7 on 2026-07-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_flujocamaras'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'unidad de muestreo',
                'verbose_name_plural': 'unidades de muestreo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMuestreoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de unidad de muestreo',
                'verbose_name_plural': 'tipos de unidad de muestreo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('tratamiento', models.CharField(blank=True, max_length=255, verbose_name='tratamiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad_muestreo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_experimentales', to='app.unidadmuestreo', verbose_name='unidad de muestreo')),
            ],
            options={
                'verbose_name': 'unidad experimental',
                'verbose_name_plural': 'unidades experimentales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='anillo',
            name='unidad_muestreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anillos', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
        migrations.AddField(
            model_name='unidadmuestreo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_muestreo', to='app.unidadmuestreotipo', verbose_name='tipo'),
        ),
    ]
