# Generated by Django 5.0.7 on 2026-07-12 02:00

from django.db import migrations


TIPOS = ["parcela", "transecto", "conglomerado", "plot"]


def seed_tipos(apps, schema_editor):
    UnidadMuestreoTipo = apps.get_model("app", "UnidadMuestreoTipo")
    for nombre in TIPOS:
        UnidadMuestreoTipo.objects.get_or_create(nombre=nombre)


def unseed_tipos(apps, schema_editor):
    UnidadMuestreoTipo = apps.get_model("app", "UnidadMuestreoTipo")
    UnidadMuestreoTipo.objects.filter(nombre__in=TIPOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_unidadmuestreo_unidadmuestreotipo_unidadexperimental_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tipos, unseed_tipos),
    ]
