# Generated by Django 5.0.7 on 2026-07-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_seed_unidad_muestreo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(choices=[('Andes', 'Andes'), ('Orinoquia', 'Orinoquía'), ('Amazonas', 'Amazonas'), ('Caribe', 'Caribe'), ('Pacifico', 'Pacífico'), ('Insular', 'Insular')], max_length=24, unique=True),
        ),
    ]
