# Generated by Django 5.0.7 on 2026-07-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_seed_regiones_departamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['nombre'], 'verbose_name': 'parcela', 'verbose_name_plural': 'parcelas'},
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='area',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='fecha_instalacion',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='sitio',
        ),
        migrations.AddField(
            model_name='parcela',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='medida_ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='medida ancho (m)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='medida_largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='medida largo (m)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='unidad_muestreo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcela', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
    ]
