# Generated by Django 5.0.7 on 2026-07-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_parcela_options_remove_parcela_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadexperimental',
            name='unidad_muestreo',
        ),
        migrations.AddField(
            model_name='unidadmuestreo',
            name='unidad_experimental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_muestreo', to='app.unidadexperimental', verbose_name='unidad experimental'),
        ),
    ]
