# Generated by Django 5.0.7 on 2026-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_unidadexperimental_unidad_muestreo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo_dane',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='código DANE'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_dane',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='código DANE'),
        ),
    ]
