# Generated by Django 5.0.7 on 2026-07-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_seed_codigos_dane_departamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoreoparcela',
            options={'verbose_name': 'monitoreo de unidad de muestreo', 'verbose_name_plural': 'monitoreos de unidad de muestreo'},
        ),
        migrations.AlterModelOptions(
            name='transecto',
            options={'ordering': ['nombre'], 'verbose_name': 'transecto', 'verbose_name_plural': 'transectos'},
        ),
        # MonitoreoParcela: agregar unidad_muestreo antes de tocar la unique_together,
        # y levantar la constraint vieja antes de quitar parcela.
        migrations.AddField(
            model_name='monitoreoparcela',
            name='unidad_muestreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoreos', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoreoparcela',
            unique_together={('unidad_muestreo', 'tipo_monitoreo')},
        ),
        migrations.RemoveField(
            model_name='monitoreoparcela',
            name='parcela',
        ),
        # Transecto: pasa a ser detalle de unidad_muestreo.
        migrations.RemoveField(
            model_name='transecto',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='transecto',
            name='sitio',
        ),
        migrations.AddField(
            model_name='transecto',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='longitud (m)'),
        ),
        migrations.AddField(
            model_name='transecto',
            name='separacion_muestreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='separación de muestreo (m)'),
        ),
        migrations.AddField(
            model_name='transecto',
            name='unidad_muestreo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transecto', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
        migrations.AlterField(
            model_name='transecto',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nombre'),
        ),
    ]
