# Generated by Django 5.0.7 on 2026-07-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_seed_municipios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadexperimental',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='mapeocolumna',
            name='valor_constante',
            field=models.CharField(blank=True, default='', help_text="Valor fijo para todas las filas cuando la transformación es 'constante' (atributo sin columna en la fuente).", max_length=500, verbose_name='valor constante'),
        ),
        migrations.AlterField(
            model_name='mapeocolumna',
            name='transformacion',
            field=models.CharField(choices=[('directo', 'Directo'), ('lookup', 'Lookup / FK'), ('split', 'Split'), ('fecha', 'Parsear fecha'), ('constante', 'Valor constante'), ('ignorar', 'Ignorar')], default='directo', max_length=20, verbose_name='transformación'),
        ),
    ]
