# Generated by Django 5.0.7 on 2026-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_unidadexperimental_tratamiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['pk'], 'verbose_name': 'parcela', 'verbose_name_plural': 'parcelas'},
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='nombre',
        ),
        migrations.AddField(
            model_name='parcela',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área (m²)'),
        ),
    ]
