# Generated by Django 5.0.7 on 2026-07-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_parcela_options_remove_parcela_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestreo',
            name='fuente_datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_muestreo', to='app.fuentedatos', verbose_name='fuente de datos'),
        ),
    ]
