# Generated by Django 5.0.7 on 2026-07-12 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_unidadmuestreo_fuente_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestreo',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_muestreo', to='app.sitio', verbose_name='sitio'),
        ),
    ]
