# Generated by Django 5.0.7 on 2026-07-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_unidadexperimental_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestraco2',
            name='anillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.anillo', verbose_name='anillo'),
        ),
        migrations.AlterField(
            model_name='muestraco2',
            name='camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.camara', verbose_name='cámara'),
        ),
    ]
