# Generated by Django 5.0.7 on 2026-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_muestraco2_anillo_camara_opcionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeocolumna',
            name='rellenar_nulos',
            field=models.BooleanField(default=False, help_text='Si la columna trae valores solo en algunas filas (p. ej. metadatos que no se repiten en cada fila), repite hacia abajo el último valor no nulo visto en vez de dejar el resto vacío.', verbose_name='rellenar nulos hacia abajo'),
        ),
    ]
