# Generated by Django 5.0.7 on 2026-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_mapeocolumna_rellenar_nulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeocolumna',
            name='rellenar_nulos',
        ),
        migrations.AddField(
            model_name='mapeocolumna',
            name='estrategia_nulos',
            field=models.CharField(choices=[('dejar_null', 'Dejar vacío'), ('rellenar', 'Rellenar hacia abajo'), ('manual', 'Ingresar valor manual'), ('ignorar_fila', 'Ignorar registros sin este valor')], default='dejar_null', help_text='Qué hacer con las filas donde esta columna viene vacía: dejarlas vacías, repetir hacia abajo el último valor visto, usar un valor fijo, o no crear el registro para esas filas.', max_length=20, verbose_name='estrategia para datos faltantes'),
        ),
        migrations.AddField(
            model_name='mapeocolumna',
            name='valor_relleno_manual',
            field=models.CharField(blank=True, default='', help_text="Valor usado para las filas vacías de esta columna cuando estrategia_nulos es 'manual'.", max_length=500, verbose_name='valor manual para nulos'),
        ),
    ]
