# Generated by Django 5.0.7 on 2026-07-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_mapeocolumna_estrategia_nulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='pks_importados',
            field=models.JSONField(blank=True, default=dict, help_text='Acumula, por modelo, los pk que esta carga creó o reutilizó al importar. Ej: {"SubmuestraCO2": [10, 11, 12]}. Permite mostrar solo los datos de esta carga en el panel de visualización.', verbose_name='pks creados/vinculados por esta carga'),
        ),
    ]
