# Generated by Django 5.0.7 on 2026-07-14 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_cargaarchivo_pks_importados'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraco2',
            name='unidad_muestreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
    ]
