# Generated by Django 5.0.7 on 2026-08-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_help_text_diccionario_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeocolumna',
            name='factor_escala',
            field=models.DecimalField(blank=True, decimal_places=10, help_text="Multiplica el valor de origen por este factor cuando la transformación es 'escala', para convertir unidades sin depender de que el archivo fuente ya venga en la unidad del campo destino (p. ej. 0.01 para pasar centímetros a metros). Solo aplica a campos numéricos.", max_digits=20, null=True, verbose_name='factor de escala'),
        ),
        migrations.AlterField(
            model_name='mapeocolumna',
            name='transformacion',
            field=models.CharField(choices=[('directo', 'Directo'), ('lookup', 'Lookup / FK'), ('split', 'Split'), ('fecha', 'Parsear fecha'), ('regex', 'Expresión regular'), ('escala', 'Conversión de unidades (factor de escala)'), ('constante', 'Valor constante'), ('ignorar', 'Ignorar')], default='directo', max_length=20, verbose_name='transformación'),
        ),
    ]
