# Generated by Django 5.0.7 on 2026-08-21 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_mapeocolumna_factor_escala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobertura',
            name='cobertura_ipcc',
            field=models.CharField(blank=True, choices=[('Tierras_forestales', 'Tierras forestales (Forest Land)'), ('Tierras_de_cultivo', 'Tierras de cultivo (Cropland)'), ('Pastizales', 'Pastizales (Grassland)'), ('Humedales', 'Humedales (Wetlands)'), ('Asentamientos', 'Asentamientos (Settlements)'), ('Otras_tierras', 'Otras tierras (Other Land)')], help_text='Categoría de uso de la tierra según el inventario IPCC de gases de efecto invernadero.', max_length=25, verbose_name='cobertura IPCC'),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='suelo_ipcc',
            field=models.CharField(blank=True, choices=[('Mineral_alta_actividad_arcilla', 'Suelos minerales de alta actividad de arcilla (HAC)'), ('Mineral_baja_actividad_arcilla', 'Suelos minerales de baja actividad de arcilla (LAC)'), ('Arenoso', 'Suelos arenosos'), ('Volcanico', 'Suelos volcánicos'), ('Organico', 'Suelos orgánicos (histosoles)'), ('Podzolico', 'Suelos podzólicos (spódicos)')], help_text='Tipo de suelo homologado a categorías IPCC.', max_length=35, verbose_name='suelo IPCC'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='tipo_localizacion',
            field=models.CharField(blank=True, choices=[('exacta', 'Localización exacta'), ('vereda', 'Aproximada a nivel de vereda (centroide DANE)'), ('municipio', 'Aproximada a nivel de municipio (centroide IGAC)'), ('inferida', 'Inferida (sin coordenadas ni vereda/municipio de referencia)')], help_text='Precisión espacial con la que se dispone la ubicación del sitio.', max_length=12, verbose_name='tipo de localización'),
        ),
        migrations.AddField(
            model_name='unidadmuestreo',
            name='compartimento',
            field=models.CharField(blank=True, choices=[('biomasa_aerea', 'Biomasa aérea'), ('biomasa_subterranea', 'Biomasa subterránea'), ('carbono_organico_suelo', 'Carbono orgánico del suelo'), ('mom_detritos', 'Materia orgánica muerta (detritos)'), ('mom_hojarasca', 'Materia orgánica muerta (hojarasca)')], help_text='Reservorio de carbono que mide esta unidad de muestreo (biomasa, COS, materia orgánica muerta).', max_length=25, verbose_name='compartimento'),
        ),
        migrations.CreateModel(
            name='MuestraBiomasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha de la medición.', null=True, verbose_name='fecha')),
                ('prod_biomasa_g', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='producción de biomasa (g)')),
                ('contenido_carbono', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='contenido de carbono')),
                ('prom_tonc_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Promedio de carbono en biomasa aérea de la parcela, en toneladas de carbono por hectárea.', max_digits=10, null=True, verbose_name='promedio (TonC/ha)')),
                ('sd_tonc_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='desviación estándar (TonC/ha)')),
                ('min_tonc_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='mínimo (TonC/ha)')),
                ('max_tonc_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='máximo (TonC/ha)')),
                ('unidad_muestreo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_biomasa', to='app.unidadmuestreo', verbose_name='unidad de muestreo')),
            ],
            options={
                'verbose_name': 'muestra de biomasa',
                'verbose_name_plural': 'muestras de biomasa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IndividuoArboreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, max_length=80, verbose_name='tipo')),
                ('n_ind', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de individuo')),
                ('condicion', models.CharField(blank=True, max_length=80, verbose_name='condición')),
                ('numero_fuste', models.CharField(blank=True, help_text='Identificador del fuste dentro del individuo, tal como lo reporta la fuente.', max_length=20, verbose_name='número de fuste')),
                ('multiples', models.CharField(blank=True, help_text='Si el individuo tiene múltiples fustes, tal como lo reporta la fuente.', max_length=20, verbose_name='múltiples')),
                ('dap_1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DAP 1 (cm)')),
                ('dap_2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DAP 2 (cm)')),
                ('dap_analisis_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DAP de análisis (cm)')),
                ('equipo', models.CharField(blank=True, max_length=120, verbose_name='equipo')),
                ('pom_m', models.DecimalField(blank=True, decimal_places=2, help_text='Point of Measurement: altura a la que se midió el DAP, en metros.', max_digits=6, null=True, verbose_name='POM (m)')),
                ('altura_fuste_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='altura del fuste (m)')),
                ('altura_total_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='altura total (m)')),
                ('diff_alturas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='diferencia de alturas (m)')),
                ('familia', models.CharField(blank=True, max_length=120, verbose_name='familia')),
                ('genero', models.CharField(blank=True, max_length=120, verbose_name='género')),
                ('especie', models.CharField(blank=True, max_length=160, verbose_name='especie')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuos', to='app.muestrabiomasa', verbose_name='muestra de biomasa')),
            ],
            options={
                'verbose_name': 'individuo arbóreo',
                'verbose_name_plural': 'individuos arbóreos',
                'ordering': ['muestra', 'n_ind'],
            },
        ),
        migrations.CreateModel(
            name='MuestraMOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha de la medición.', null=True, verbose_name='fecha')),
                ('carbono_mom_valor_reportado', models.DecimalField(blank=True, decimal_places=4, help_text='Contenido de carbono en MOM, valor tal como lo reporta la fuente.', max_digits=12, null=True, verbose_name='carbono MOM (valor reportado)')),
                ('carbono_mom_tc_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='carbono MOM total (tC/ha)')),
                ('error_mom', models.CharField(blank=True, max_length=80, verbose_name='medida de error MOM (SD;EE;U%)')),
                ('carbono_amp_tm_tc_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Carbono en árboles muertos en pie (AMP) y tocones muertos (TM), en toneladas de carbono por hectárea.', max_digits=10, null=True, verbose_name='carbono AMP+TM (tC/ha)')),
                ('error_amp_tm', models.CharField(blank=True, max_length=80, verbose_name='medida de error AMP_TM (SD;EE;U%)')),
                ('carbono_dfm_tc_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Carbono en detritos finos de madera (DFM), en toneladas de carbono por hectárea.', max_digits=10, null=True, verbose_name='carbono DFM (tC/ha)')),
                ('error_dfm', models.CharField(blank=True, max_length=80, verbose_name='medida de error DFM (SD;EE;U%)')),
                ('carbono_dgm_tc_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Carbono en detritos gruesos de madera (DGM), en toneladas de carbono por hectárea.', max_digits=10, null=True, verbose_name='carbono DGM (tC/ha)')),
                ('error_dgm', models.CharField(blank=True, max_length=80, verbose_name='medida de error DGM (SD;EE;U%)')),
                ('carbono_hojarasca_g_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='carbono en hojarasca (g/m²)')),
                ('carbono_hojarasca_tc_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='carbono en hojarasca (tC/ha)')),
                ('error_hojarasca', models.CharField(blank=True, max_length=80, verbose_name='medida de error hojarasca (SD;EE;U%)')),
                ('metodologia_muestreo_mom', models.CharField(blank=True, max_length=255, verbose_name='metodología: muestreo MOM')),
                ('metodologia_muestreo_dfm_dgm', models.CharField(blank=True, max_length=255, verbose_name='metodología: muestreo DFM-DGM')),
                ('metodologia_tamano', models.CharField(blank=True, max_length=255, verbose_name='metodología: tamaño')),
                ('metodologia_amp_to', models.CharField(blank=True, max_length=255, verbose_name='metodología: AMP y TO')),
                ('metodologia_hojarasca', models.CharField(blank=True, max_length=255, verbose_name='metodología: hojarasca')),
                ('unidad_muestreo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muestras_mom', to='app.unidadmuestreo', verbose_name='unidad de muestreo')),
            ],
            options={
                'verbose_name': 'muestra de materia orgánica muerta',
                'verbose_name_plural': 'muestras de materia orgánica muerta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SubmuestraSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha en la que se realizó la toma.', null=True, verbose_name='fecha')),
                ('hora', models.TimeField(blank=True, help_text='Hora en la que se realizó la toma.', null=True, verbose_name='hora')),
                ('barreno_vol', models.CharField(blank=True, help_text='Identificador o volumen del barreno/cilindro usado para la toma, tal como lo reporta la fuente.', max_length=80, verbose_name='barreno / volumen')),
                ('profundidad_desde_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Límite superior del intervalo de profundidad muestreado, en centímetros.', max_digits=8, null=True, verbose_name='profundidad desde (cm)')),
                ('profundidad_hasta_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Límite inferior del intervalo de profundidad muestreado, en centímetros.', max_digits=8, null=True, verbose_name='profundidad hasta (cm)')),
                ('densidad_aparente_g_cm3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='densidad aparente (g/cm³)')),
                ('carbono_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Porcentaje de carbono orgánico medido en la toma.', max_digits=8, null=True, verbose_name='% carbono')),
                ('soil_chem_c_org', models.DecimalField(blank=True, decimal_places=4, help_text='Carbono orgánico del suelo reportado por la fuente (SOIL_CHEM_C_ORG).', max_digits=8, null=True, verbose_name='SOIL_CHEM_C_ORG')),
                ('medida_error', models.CharField(blank=True, help_text='Error asociado reportado por la fuente: desviación estándar (SD), error estándar (EE) o incertidumbre (U%).', max_length=80, verbose_name='medida de error (SD;EE;U%)')),
                ('metodologia_tipo_muestreo', models.CharField(blank=True, max_length=255, verbose_name='metodología: tipo de muestreo')),
                ('metodologia_distancia_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='metodología: distancia (m)')),
                ('metodologia_azimut', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='metodología: azimut (°)')),
                ('metodologia_analisis', models.CharField(blank=True, max_length=255, verbose_name='metodología: método de análisis')),
                ('unidad_muestreo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submuestras_suelo', to='app.unidadmuestreo', verbose_name='unidad de muestreo')),
            ],
            options={
                'verbose_name': 'submuestra de suelo',
                'verbose_name_plural': 'submuestras de suelo',
                'ordering': ['unidad_muestreo', 'profundidad_desde_cm'],
            },
        ),
    ]
