# Generated by Django 5.0.7 on 2026-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_cobertura_cobertura_ipcc_cobertura_suelo_ipcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disturbio',
            name='estado_conservacion',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural (sin manejo humano significativo)'), ('Seminatural', 'Seminatural (manejo bajo, regeneración natural dominante)'), ('Manejado', 'Manejado (aprovechamiento, ganadería, agroforestería)'), ('Plantacion', 'Plantación (vegetación establecida y manejada)'), ('Artificial_Urbano', 'Artificial / Urbano (superficie no natural)')], help_text='Estado del ecosistema frente a la presencia de manejo humano (taxonomía del vocabulario IDEAM).', max_length=20, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='disturbio',
            name='proteccion_legal',
            field=models.TextField(blank=True, help_text='Si el sitio está bajo alguna figura de reserva, parque, santuario, etc.', verbose_name='protección legal'),
        ),
    ]
