# Generated by Django 5.0.7 on 2026-08-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_disturbio_estado_conservacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='suelo_ipcc',
            field=models.CharField(blank=True, choices=[('Mineral', 'Suelos minerales (sin subtipo especificado)'), ('Mineral_alta_actividad_arcilla', 'Suelos minerales de alta actividad de arcilla (HAC)'), ('Mineral_baja_actividad_arcilla', 'Suelos minerales de baja actividad de arcilla (LAC)'), ('Arenoso', 'Suelos arenosos'), ('Volcanico', 'Suelos volcánicos'), ('Organico', 'Suelos orgánicos (histosoles)'), ('Podzolico', 'Suelos podzólicos (spódicos)')], help_text='Tipo de suelo homologado a categorías IPCC.', max_length=35, verbose_name='suelo IPCC'),
        ),
    ]
