# Generated by Django 5.0.7 on 2026-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_cobertura_eav_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='simbolo',
            field=models.CharField(blank=True, help_text='Símbolo corto para mostrar en las tablas de datos (ej. µmol m-2 s-1), en vez del código interno.', max_length=40, verbose_name='unidad del flujo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del equipo analizador (ej. Picarro G4301, LI-7810).', max_length=120, verbose_name='analizador'),
        ),
    ]
