# Generated by Django 5.0.7 on 2026-09-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_seed_rol_basico'),
        ('app', '0088_usuario_nivel_acceso'),
    ]

    operations = [
    ]
