# Generated by Django 5.0.7 on 2026-09-15 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_merge_0087_seed_rol_basico_0088_usuario_nivel_acceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_solicitado', models.CharField(choices=[('investigador', 'Investigador'), ('reportador', 'Reportador'), ('admin', 'Administrador')], max_length=20, verbose_name='nivel solicitado')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to='app.usuario', verbose_name='resuelta por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_nivel', to='app.usuario', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'solicitud de nivel',
                'verbose_name_plural': 'solicitudes de nivel',
                'ordering': ['-created_at'],
            },
        ),
    ]
