# Generated by Django 5.0.7 on 2026-09-18 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_solicitudnivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expira_en', models.DateTimeField(verbose_name='expira en')),
                ('usado', models.BooleanField(default=False, verbose_name='usado')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='cuenta de acceso')),
            ],
            options={
                'verbose_name': 'token de recuperación de contraseña',
                'verbose_name_plural': 'tokens de recuperación de contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
