# Generated by Django 5.0.7 on 2026-09-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_cargaarchivo_origen_mapeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadexperimental',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo de unidad de muestreo (parcela, transecto, conglomerado, plot, etc.). Es un catálogo cerrado: se elige entre los tipos ya existentes, no se crean tipos nuevos al cargar datos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_experimentales', to='app.unidadmuestreotipo', verbose_name='tipo'),
        ),
    ]
