# Generated by Django 5.0.7 on 2026-09-23 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_unidad_experimental_tipo_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='compartimento',
            field=models.CharField(blank=True, choices=[('biomasa_aerea', 'Biomasa aérea'), ('biomasa_subterranea', 'Biomasa subterránea'), ('carbono_organico_suelo', 'Carbono orgánico del suelo'), ('mom_detritos', 'Materia orgánica muerta (detritos)'), ('mom_hojarasca', 'Materia orgánica muerta (hojarasca)')], help_text='Reservorio de carbono que mide esta unidad de muestreo, solo si el mismo punto/parcela se divide en unidades distintas por tipo de medición (ej. una parcela para biomasa y otra para suelo dentro de la misma unidad experimental). Déjalo vacío si no aplica.', max_length=25, verbose_name='compartimento'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='sitio',
            field=models.ForeignKey(blank=True, help_text='Sitio de ubicación de esta unidad de muestreo. Se vincula solo al guardar la sección Sitio (por la fila del archivo), no se mapea acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_muestreo', to='app.sitio', verbose_name='sitio'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de unidad de muestreo (parcela, transecto, conglomerado, plot, etc.). Es un catálogo cerrado: se elige entre los tipos ya existentes, no se crean tipos nuevos al cargar datos.', on_delete=django.db.models.deletion.PROTECT, related_name='unidades_muestreo', to='app.unidadmuestreotipo', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='unidad_experimental',
            field=models.ForeignKey(blank=True, help_text='Unidad experimental a la que pertenece. Se resuelve sola con la que se creó o seleccionó en el paso anterior para la misma fila del archivo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_muestreo', to='app.unidadexperimental', verbose_name='unidad experimental'),
        ),
    ]
