# Generated by Django 5.0.7 on 2026-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_unidad_muestreo_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeocolumna',
            name='gas_fijo',
            field=models.CharField(blank=True, choices=[('CO2', 'CO₂'), ('CH4', 'CH₄'), ('N2O', 'N₂O')], help_text="Solo aplica cuando modelo_destino es 'SubmuestraGEI' y campo_destino es 'valor': fija a qué gas (CO₂, CH₄, N₂O) corresponde esta columna, para archivos que traen el flujo de cada gas en su propia columna (formato ancho) en vez de una columna 'gas' + una columna 'valor' (formato largo). Cada columna con gas_fijo genera su propio par MuestraGEI/SubmuestraGEI por fila.", max_length=4, verbose_name='gas fijo'),
        ),
    ]
