# Generated by Django 5.0.7 on 2026-09-24 16:56

from django.db import migrations, models


def backfill_hoja(apps, schema_editor):
    """Rellena MapeoColumna.hoja y CargaArchivo.hojas para cargas existentes,
    a partir del único hoja_activa/columnas_raw/total_filas que tenían antes
    de que una carga pudiera abarcar varias hojas."""
    CargaArchivo = apps.get_model('app', 'CargaArchivo')
    MapeoColumna = apps.get_model('app', 'MapeoColumna')

    for carga in CargaArchivo.objects.exclude(hoja_activa='').iterator():
        MapeoColumna.objects.filter(carga=carga, hoja='').update(hoja=carga.hoja_activa)
        carga.hojas = {
            carga.hoja_activa: {
                'columnas_raw': carga.columnas_raw,
                'total_filas': carga.total_filas,
            }
        }
        carga.save(update_fields=['hojas'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_mapeocolumna_gas_fijo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapeocolumna',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='hojas',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot por hoja del archivo (excluye hojas de "diccionario de datos"): {"CO2 (detalle)": {"columnas_raw": [...], "total_filas": 346}, ...}. Permite mapear varias hojas del mismo archivo en un solo flujo, sin crear una carga por hoja.', verbose_name='hojas analizadas'),
        ),
        migrations.AddField(
            model_name='mapeocolumna',
            name='hoja',
            field=models.CharField(blank=True, help_text='Hoja del archivo de la que viene columna_origen. Permite que una misma carga mapee varias hojas del Excel (p. ej. Unidad Muestreo-Experimental, CO2 (detalle), Clima) a la vez.', max_length=255, verbose_name='hoja'),
        ),
        migrations.AlterField(
            model_name='cargaarchivo',
            name='columnas_raw',
            field=models.JSONField(default=list, help_text='Snapshot de columnas de `hoja_activa`. Para todas las hojas ver `hojas`.', verbose_name='columnas inspeccionadas'),
        ),
        migrations.AlterField(
            model_name='cargaarchivo',
            name='hoja_activa',
            field=models.CharField(blank=True, help_text='Última hoja abierta en el asistente de mapeo. No es la única hoja de la carga — ver `hojas`.', max_length=255, verbose_name='hoja activa'),
        ),
        migrations.RunPython(backfill_hoja, noop),
        migrations.AlterUniqueTogether(
            name='mapeocolumna',
            unique_together={('carga', 'hoja', 'columna_origen', 'modelo_destino', 'campo_destino')},
        ),
    ]
