# Generated by Django 5.0.7 on 2026-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_mapeocolumna_hoja_carga_hojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeocolumna',
            name='hoja_origen',
            field=models.CharField(blank=True, help_text='Si columna_origen viene de una hoja distinta a `hoja` (la hoja de contexto de este mapeo, la que se está escribiendo), el nombre de esa otra hoja. Vacío = misma hoja. Permite mapear un atributo de una sección usando una columna de otra hoja del mismo archivo, cruzando filas por una clave común (ver _CLAVES_JOIN_HOJAS en etl/views.py).', max_length=255, verbose_name='hoja origen de la columna'),
        ),
    ]
