# Generated by Django 5.0.7 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_mapeocolumna_hoja_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='progreso_actual',
            field=models.IntegerField(default=0, verbose_name='progreso actual'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='progreso_estado',
            field=models.CharField(choices=[('idle', 'Sin iniciar'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('error', 'Error')], default='idle', help_text='Importar corre en un hilo en background (no hay worker separado); este campo permite que el frontend haga polling del avance en vez de bloquear la petición HTTP.', max_length=20, verbose_name='estado del progreso de importación'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='progreso_mensaje',
            field=models.CharField(blank=True, max_length=255, verbose_name='mensaje de progreso'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='progreso_resultado',
            field=models.JSONField(blank=True, help_text='Mismo shape que hoy devuelve el endpoint de importación de forma síncrona, guardado aquí cuando progreso_estado pasa a completado/error.', null=True, verbose_name='resultado final de la importación'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='progreso_total',
            field=models.IntegerField(default=0, verbose_name='progreso total'),
        ),
    ]
